server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/numery009/rsmortgage-config-repository
          searchPaths: rsmortgage-customer-service
          