

####################################
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          https://github.com/numery009/rsmortgage-config-repository
          searchPaths: rsmortgage-customer-service,rsmortgage-customer-account-service
          username: username
          password: password
